services:
  nginx:
    container_name: reverse-proxy-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - shared-proxy
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: always

networks:
  shared-proxy:
    external: true